### ISSUE TITLE
missing .netrc file setup instructions required for direct S3 access

### ISSUE THREAD

**Issue by GMoncrieff** [nasa/EMIT-Data-Resources#33]
commit [6958963](https://github.com/nasa/EMIT-Data-Resources/commit/6958963cfafeff32ef03d51e125e3c481988e8ba) removes the setup instructions to create the .netrc file, but this is required for direct S3 access as described in [How_to_Direct_S3_Access.ipynb](https://github.com/nasa/EMIT-Data-Resources/blob/main/python/how-tos/How_to_Direct_S3_Access.ipynb) notebook

**Comment by GMoncrieff** [comment]
oh I see that `earthaccess.login(persist=True)` writes the .netrc file. But the text in the notebook needs to be updated to reflect this

**Comment by ebolch** [comment]
Thanks for pointing this out. [PR #37](https://github.com/nasa/EMIT-Data-Resources/pull/37) updates the instructions within the notebook and adds the use of `earthaccess` to create and/or add NASA Earthdata credentials to the .netrc file.
