### ISSUE TITLE
s3 access EMIT data

### ISSUE THREAD

**Issue by kleinlevente** [nasa/EMIT-Data-Resources#50]
Trying to run the s3 access notebook :
https://github.com/nasa/EMIT-Data-Resources/blob/main/python/how-tos/How_to_Direct_S3_Access.ipynb
but I am running in an access error:
ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden

The above exception was the direct cause of the following exception:

PermissionError                           Traceback (most recent call last)
Cell In[9], line 2
      1 # Open s3 url
----> 2 fp = fs_s3.open(s3_url, mode='rb')
      3 # Open dataset with xarray
      4 ds = xr.open_dataset(fp) #Note this only opens the root group (reflectance)

with a final error:
PermissionError: Forbidden

I assume this is a setting issue on the COS bucket where access is defined.

**Comment by amfriesz** [comment]
Hey @kleinlevente,

Are you running the code from a compute instance in AWS us-west-2? Direct S3 access of NASA assets is only allowed if you are working from us-west-2. In all other situations, e.g. working locally, from another AWS region, or from another cloud provider, you would need to use the HTTPS URLS associated with the data assets.
