### ISSUE TITLE
Add EMIT L2B Mineralogy Tutorial to the Repository Contents Table

### ISSUE THREAD

**Issue by cpkrehbiel** [nasa/EMIT-Data-Resources#62]
I don't see the new EMIT L2B Mineralogy Data tutorial (https://github.com/nasa/EMIT-Data-Resources/blob/main/python/tutorials/Working_with_EMIT_L2B_Mineralogy.ipynb) listed in the Repository Contents table here: https://github.com/nasa/EMIT-Data-Resources

**Comment by ebolch** [comment]
Thanks for the reminder. Added mineral tutorials and the QGIS NASA Earthdata COG Streaming Guide.
